'use strict';

// Name generator for cards

const Util = require('./util.js');

const _ = require('lodash');

class CardName {
    static random () {
        const nameGender = _.sample('female', 'male');

        const givenName = nameGender === 'female' ?
            _.sample(CardName.femaleGivenNames()) :
            _.sample(CardName.maleGivenNames());

        const familyName = Util.capitalized(
            _.sample(CardName.familyNames()).toLowerCase()
        );

        return givenName + ' ' + familyName;
    }

    static femaleGivenNames () {
        return [
            'Mary',
            'Patricia',
            'Jennifer',
            'Linda',
            'Elizabeth',
            'Barbara',
            'Susan',
            'Jessica',
            'Sarah',
            'Karen',
            'Nancy',
            'Margaret',
            'Lisa',
            'Betty',
            'Dorothy',
            'Sandra',
            'Ashley',
            'Kimberly',
            'Donna',
            'Emily',
            'Michelle',
            'Carol',
            'Amanda',
            'Melissa',
            'Deborah',
            'Stephanie',
            'Rebecca',
            'Laura',
            'Sharon',
            'Cynthia',
            'Kathleen',
            'Helen',
            'Amy',
            'Shirley',
            'Angela',
            'Anna',
            'Brenda',
            'Pamela',
            'Nicole',
            'Ruth',
            'Katherine',
            'Samantha',
            'Christine',
            'Emma',
            'Catherine',
            'Debra',
            'Virginia',
            'Rachel',
            'Carolyn',
            'Janet'
        ];
    }

    static maleGivenNames () {
        return [
            'John',
            'Robert',
            'Michael',
            'William',
            'David',
            'Richard',
            'Joseph',
            'Thomas',
            'Charles',
            'Christopher',
            'Daniel',
            'Matthew',
            'Anthony',
            'Donald',
            'Mark',
            'Paul',
            'Steven',
            'Andrew',
            'Kenneth',
            'Joshua',
            'George',
            'Kevin',
            'Brian',
            'Edward',
            'Ronald',
            'Timothy',
            'Jason',
            'Jeffrey',
            'Ryan',
            'Jacob',
            'Gary',
            'Nicholas',
            'Eric',
            'Stephen',
            'Jonathan',
            'Larry',
            'Justin',
            'Scott',
            'Brandon',
            'Frank',
            'Benjamin',
            'Gregory',
            'Samuel',
            'Raymond',
            'Patrick',
            'Alexander',
            'Jack',
            'Dennis',
            'Jerry'
        ];
    }

    static familyNames () {
        return [
            // LATER decapitalize.
            'SMITH',
            'JOHNSON',
            'WILLIAMS',
            'BROWN',
            'JONES',
            'GARCIA',
            'MILLER',
            'DAVIS',
            'RODRIGUEZ',
            'MARTINEZ',
            'HERNANDEZ',
            'LOPEZ',
            'GONZALEZ',
            'WILSON',
            'ANDERSON',
            'THOMAS',
            'TAYLOR',
            'MOORE',
            'JACKSON',
            'MARTIN',
            'LEE',
            'PEREZ',
            'THOMPSON',
            'WHITE',
            'HARRIS',
            'SANCHEZ',
            'CLARK',
            'RAMIREZ',
            'LEWIS',
            'ROBINSON',
            'WALKER',
            'YOUNG',
            'ALLEN',
            'KING',
            'WRIGHT',
            'SCOTT',
            'TORRES',
            'NGUYEN',
            'HILL',
            'FLORES',
            'GREEN',
            'ADAMS',
            'NELSON',
            'BAKER',
            'HALL',
            'RIVERA',
            'CAMPBELL',
            'MITCHELL',
            'CARTER',
            'ROBERTS',
            'GOMEZ',
            'PHILLIPS',
            'EVANS',
            'TURNER',
            'DIAZ',
            'PARKER',
            'CRUZ',
            'EDWARDS',
            'COLLINS',
            'REYES',
            'STEWART',
            'MORRIS',
            'MORALES',
            'MURPHY',
            'COOK',
            'ROGERS',
            'GUTIERREZ',
            'ORTIZ',
            'MORGAN',
            'COOPER',
            'PETERSON',
            'BAILEY',
            'REED',
            'KELLY',
            'HOWARD',
            'RAMOS',
            'KIM',
            'COX',
            'WARD',
            'RICHARDSON',
            'WATSON',
            'BROOKS',
            'CHAVEZ',
            'WOOD',
            'JAMES',
            'BENNETT',
            'GRAY',
            'MENDOZA',
            'RUIZ',
            'HUGHES',
            'PRICE',
            'ALVAREZ',
            'CASTILLO',
            'SANDERS',
            'PATEL',
            'MYERS',
            'LONG',
            'ROSS',
            'FOSTER',
            'JIMENEZ'
        ];
    }
}

module.exports = CardName;
